# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ReservationRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_id: str=None, reservation_details: str=None):  # noqa: E501
        """ReservationRequest - a model defined in Swagger

        :param user_id: The user_id of this ReservationRequest.  # noqa: E501
        :type user_id: str
        :param reservation_details: The reservation_details of this ReservationRequest.  # noqa: E501
        :type reservation_details: str
        """
        self.swagger_types = {
            'user_id': str,
            'reservation_details': str
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'reservation_details': 'reservation_details'
        }
        self._user_id = user_id
        self._reservation_details = reservation_details

    @classmethod
    def from_dict(cls, dikt) -> 'ReservationRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReservationRequest of this ReservationRequest.  # noqa: E501
        :rtype: ReservationRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this ReservationRequest.


        :return: The user_id of this ReservationRequest.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this ReservationRequest.


        :param user_id: The user_id of this ReservationRequest.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def reservation_details(self) -> str:
        """Gets the reservation_details of this ReservationRequest.


        :return: The reservation_details of this ReservationRequest.
        :rtype: str
        """
        return self._reservation_details

    @reservation_details.setter
    def reservation_details(self, reservation_details: str):
        """Sets the reservation_details of this ReservationRequest.


        :param reservation_details: The reservation_details of this ReservationRequest.
        :type reservation_details: str
        """
        if reservation_details is None:
            raise ValueError("Invalid value for `reservation_details`, must not be `None`")  # noqa: E501

        self._reservation_details = reservation_details
