name: Deploy to Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      # Install shared dependencies for functions (if any)
      - name: Install function dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt -t db_layer/python
          fi

      ##############################
      # Build & Publish the Layer  #
      ##############################
      - name: Package Layer
        run: |
          # Ensure the layer package has a "python" folder at its root
          cd db_layer
          zip -r ../db_layer.zip .
          cd ..
      - name: Publish Lambda Layer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          
          aws lambda publish-layer-version \
            --layer-name my-db-layer \
            --zip-file fileb://db_layer.zip \
            --compatible-runtimes python3.13

      #########################################
      # Package & Deploy items_method Lambda  #
      #########################################
      - name: Package items_method function
        run: |
          cd src
          zip -r items_method.zip items_method.py
          cd ..
      - name: Deploy items_method Lambda Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          source scripts/check_update.sh
          aws lambda update-function-code \
            --function-name items_method \
            --zip-file fileb://src/items_method.zip
          check_update items_method
      - name: Update items_method Function Configuration (set handler)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          source scripts/check_update.sh
          aws lambda update-function-configuration \
            --function-name items_method \
            --handler items_method.lambda_handler
          check_update items_method

      ###################################################
      # Package & Deploy items_item_id_methods Lambda   #
      ###################################################
      - name: Package items_item_id_methods function
        run: |
          cd src
          zip -r items_item_id_methods.zip items_item_id_methods.py
          cd ..
      - name: Deploy items_item_id_methods Lambda Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          source scripts/check_update.sh
          aws lambda update-function-code \
            --function-name items_item_id_methods \
            --zip-file fileb://src/items_item_id_methods.zip
          check_update items_method
      - name: Update items_item_id_methods Function Configuration (set handler)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          source scripts/check_update.sh
          aws lambda update-function-configuration \
            --function-name items_item_id_methods \
            --handler items_item_id_methods.lambda_handler
          check_update items_method
      ###################################################
      # Package & Deploy items_item_id__purchase_methods Lambda   #
      ###################################################
      - name: Package items_item_id_methods function
        run: |
          cd src
          zip -r items_item_id_purchase_methods.zip items_item_id_purchase_methods.py
          cd ..
      - name: Deploy items_item_id_purchase_methods Lambda Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          source scripts/check_update.sh
          aws lambda update-function-code \
            --function-name items_item_id_purchase_methods \
            --zip-file fileb://src/items_item_id_purchase_methods.zip
          check_update items_method
      - name: Update items_item_id_purchase_methods Function Configuration (set handler)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          source scripts/check_update.sh
          aws lambda update-function-configuration \
            --function-name items_item_id_purchase_methods \
            --handler items_item_id_purchase_methods.lambda_handler
          check_update items_method
      ###################################################
      # Package & Deploy items_item_id_reservations_methods Lambda   #
      ###################################################
      - name: Package items_item_id_reservations_methods function
        run: |
          cd src
          zip -r items_item_id_reservations_methods.zip items_item_id_reservations_methods.py
          cd ..
      - name: Deploy items_item_id_reservations_methods Lambda Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          source scripts/check_update.sh
          aws lambda update-function-code \
            --function-name items_item_id_reservations_methods \
            --zip-file fileb://src/items_item_id_reservations_methods.zip
          check_update items_method
      - name: Update items_item_id_reservations_methods Function Configuration (set handler)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws lambda update-function-configuration \
            --function-name items_item_id_reservations_methods \
            --handler items_item_id_reservations_methods.lambda_handler
          check_update items_method

      ###################################################
      # Package & Deploy location_methods Lambda   #
      ###################################################
      - name: Package location_methods function
        run: |
          cd src
          zip -r location_methods.zip location_methods.py
          cd ..
      - name: Deploy location_methods Lambda Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          source scripts/check_update.sh
          aws lambda update-function-code \
            --function-name location_methods \
            --zip-file fileb://src/location_methods.zip
          check_update items_method
      - name: Update location_methods Function Configuration (set handler)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          source scripts/check_update.sh
          aws lambda update-function-configuration \
            --function-name location_methods \
            --handler location_methods.lambda_handler
          check_update items_method

      ###################################################
      # Package & Deploy reservations_reservation_id_method Lambda   #
      ###################################################
      - name: Package reservations_reservation_id_method function
        run: |
          cd src
          zip -r reservations_reservation_id_method.zip reservations_reservation_id_method.py
          cd ..
      - name: Deploy reservations_reservation_id_method Lambda Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          source scripts/check_update.sh
          aws lambda update-function-code \
            --function-name reservations_reservation_id_method \
            --zip-file fileb://src/reservations_reservation_id_method.zip
          check_update items_method
      - name: Update reservations_reservation_id_method Function Configuration (set handler)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          source scripts/check_update.sh
          aws lambda update-function-configuration \
            --function-name reservations_reservation_id_method \
            --handler reservations_reservation_id_method.lambda_handler
          check_update items_method
      ###################################################
      # Package & Deploy items_item_id_location_location_id_method Lambda   #
      ###################################################
      - name: Package items_item_id_location_location_id_method function
        run: |
          cd src
          zip -r items_item_id_location_location_id_method.zip items_item_id_location_location_id_method.py
          cd ..
      - name: Deploy items_item_id_location_location_id_method Lambda Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          source scripts/check_update.sh
          aws lambda update-function-code \
            --function-name items_item_id_location_location_id_method \
            --zip-file fileb://src/items_item_id_location_location_id_method.zip
          check_update items_method
      - name: Update items_item_id_location_location_id_method Function Configuration (set handler)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          source scripts/check_update.sh
          aws lambda update-function-configuration \
            --function-name items_item_id_location_location_id_method \
            --handler items_item_id_location_location_id_method.lambda_handler
          check_update items_method
          